"""add fr key from exponat to locatin

Revision ID: d7af87a9e84a
Revises: 208f7670c163
Create Date: 2024-10-16 23:48:17.061103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7af87a9e84a'
down_revision: Union[str, None] = '208f7670c163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exponat', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exponat', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exponat', type_='foreignkey')
    op.drop_column('exponat', 'location_id')
    # ### end Alembic commands ###
